### PR TITLE
Implementation changes for McMakler

### PR DESCRIPTION
**Pull request by TheRungtaLibrary**
Hi, 

This is the Implementation changes for McMakler - Please go through the README-DEVELOPER GUIDE.md

### CODE REVIEW

**Comment by OskHa** [comment]
Hello @TheRungtaLibrary. You have been asked to fork and not make a pull request.

**Comment by TheRungtaLibrary** [comment]
Hi Oshka, I have forked and implemented the changes on my oen repository. Howwever, there are no specific instructions given on how that code will be tested by recruitment team at McMakler. Hence the pull request for the changes implemented. Kindly let me know how are you planning to proceed with this.

**Comment by TheRungtaLibrary** [comment]
Hi,

I have forked and implemented the changes on my own repository. However,
there are no specific instructions given on how that code will be tested by
recruitment team at McMakler. Hence the pull request for the changes
implemented. Kindly let me know how are you planning to proceed with this.

Regards,
Tushar Rungta

**Comment by TheRungtaLibrary** [comment]
Hi,

The following is the forked repository url - https://github.com/TheRungtaLibrary/frontend_interview_test

Regards,
Tushar Rungta

**Comment by TheRungtaLibrary** [comment]
Hi,

The following is the forked repository url -
https://github.com/TheRungtaLibrary/frontend_interview_test

Regards,
Tushar Rungta

**Pull request closed without merging**
